import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class Category{
  final int id;
  final String name;
  final dynamic icon;
  Category(this.id, this.name, {this.icon});

}

//final List<Category> categories = [
//  Category(9,"General Knowledge", icon: FontAwesomeIcons.globeAsia),
//  Category(10,"Books", icon: FontAwesomeIcons.bookOpen),
//  Category(11,"Film", icon: FontAwesomeIcons.video),
//  Category(12,"Music", icon: FontAwesomeIcons.music),
//  Category(13,"Musicals & Theatres", icon: FontAwesomeIcons.theaterMasks),
//  Category(14,"Television", icon: FontAwesomeIcons.tv),
//  Category(15,"Video Games", icon: FontAwesomeIcons.gamepad),
//  Category(16,"Board Games", icon: FontAwesomeIcons.chessBoard),
//  Category(17,"Science & Nature", icon: FontAwesomeIcons.microscope),
//  Category(18,"Computer", icon: FontAwesomeIcons.laptopCode),
//  Category(19,"Maths", icon: FontAwesomeIcons.sortNumericDown),
//  Category(20,"Mythology"),
//  Category(21,"Sports", icon: FontAwesomeIcons.footballBall),
//  Category(22,"Geography", icon: FontAwesomeIcons.mountain),
//  Category(23,"History", icon: FontAwesomeIcons.monument),
//  Category(24,"Politics"),
//  Category(25,"Art", icon: FontAwesomeIcons.paintBrush),
//  Category(26,"Celebrities"),
//  Category(27,"Animals", icon: FontAwesomeIcons.dog),
//  Category(28,"Vehicles", icon: FontAwesomeIcons.carAlt),
//  Category(29,"Comics"),
//  Category(30,"Gadgets", icon: FontAwesomeIcons.mobileAlt),
//  Category(31,"Japanese Anime & Manga"),
//  Category(32,"Cartoon & Animation"),
//];

//final List<Category> categories = [
//  Category(1,"Juz 1", icon: FontAwesomeIcons.bookOpen),
//  Category(2,"Juz 2", icon: FontAwesomeIcons.bookOpen),
//  Category(3,"Juz 3", icon: FontAwesomeIcons.bookOpen),
//  Category(4,"Juz 4", icon: FontAwesomeIcons.bookOpen),
//  Category(5,"Juz 5", icon: FontAwesomeIcons.bookOpen),
//  Category(6,"Juz 6", icon: FontAwesomeIcons.bookOpen),
//  Category(7,"Juz 7", icon: FontAwesomeIcons.bookOpen),
//  Category(8,"Juz 8", icon: FontAwesomeIcons.bookOpen),
//  Category(9,"Juz 9", icon: FontAwesomeIcons.bookOpen),
//  Category(10,"Juz 10", icon: FontAwesomeIcons.bookOpen),
//  Category(11,"Juz 11", icon: FontAwesomeIcons.bookOpen),
//  Category(12,"Juz 12", icon: FontAwesomeIcons.bookOpen),
//  Category(13,"Juz 13", icon: FontAwesomeIcons.bookOpen),
//  Category(14,"Juz 14", icon: FontAwesomeIcons.bookOpen),
//  Category(15,"Juz 15", icon: FontAwesomeIcons.bookOpen),
//  Category(16,"Juz 16", icon: FontAwesomeIcons.bookOpen),
//  Category(17,"Juz 17", icon: FontAwesomeIcons.bookOpen),
//  Category(18,"Juz 18", icon: FontAwesomeIcons.bookOpen),
//  Category(19,"Juz 19", icon: FontAwesomeIcons.bookOpen),
//  Category(20,"Juz 20", icon: FontAwesomeIcons.bookOpen),
//  Category(21,"Juz 21", icon: FontAwesomeIcons.bookOpen),
//  Category(22,"Juz 22", icon: FontAwesomeIcons.bookOpen),
//  Category(23,"Juz 23", icon: FontAwesomeIcons.bookOpen),
//  Category(24,"Juz 24", icon: FontAwesomeIcons.bookOpen),
//  Category(25,"Juz 25", icon: FontAwesomeIcons.bookOpen),
//  Category(26,"Juz 26", icon: FontAwesomeIcons.bookOpen),
//  Category(27,"Juz 27", icon: FontAwesomeIcons.bookOpen),
//  Category(28,"Juz 28", icon: FontAwesomeIcons.bookOpen),
//  Category(29,"Juz 29", icon: FontAwesomeIcons.bookOpen),
//  Category(30,"Juz 30", icon: FontAwesomeIcons.bookOpen)
//];

//final List<Category> categories = [
//  Category(1 ,"Surah:1 Al-Faatiha", icon: FontAwesomeIcons.bookOpen),
//  Category(2 ,"Surah:2 Al-Baqara", icon: FontAwesomeIcons.bookOpen),
//  Category(3 ,"Surah:3 Aal-i-Imraan", icon: FontAwesomeIcons.bookOpen),
//  Category(4 ,"Surah:4 An-Nisaa", icon: FontAwesomeIcons.bookOpen),
//  Category(5 ,"Surah:5 Al-Maaida", icon: FontAwesomeIcons.bookOpen),
//  Category(6 ,"Surah:6 Al-An'aam", icon: FontAwesomeIcons.bookOpen),
//  Category(7 ,"Surah:7 Al-A'raaf", icon: FontAwesomeIcons.bookOpen),
//  Category(8 ,"Surah:8 Al-Anfaal", icon: FontAwesomeIcons.bookOpen),
//  Category(9 ,"Surah:9 At-Tawba", icon: FontAwesomeIcons.bookOpen),
//  Category(10,"Surah:10 Yunus", icon: FontAwesomeIcons.bookOpen),
//  Category(11,"Surah:11 Hud", icon: FontAwesomeIcons.bookOpen),
//  Category(12,"Surah:12 Yusuf", icon: FontAwesomeIcons.bookOpen),
//  Category(13,"Surah:13 Ar-Ra'd", icon: FontAwesomeIcons.bookOpen),
//  Category(14,"Surah:14 Ibrahim", icon: FontAwesomeIcons.bookOpen),
//  Category(15,"Surah:15 Al-Hijr", icon: FontAwesomeIcons.bookOpen),
//  Category(16,"Surah:16 An-Nahl", icon: FontAwesomeIcons.bookOpen),
//  Category(17,"Surah:17 Al-Israa", icon: FontAwesomeIcons.bookOpen),
//  Category(18,"Surah:18 Al-Kahf", icon: FontAwesomeIcons.bookOpen),
//  Category(19,"Surah:19 Maryam", icon: FontAwesomeIcons.bookOpen),
//  Category(20,"Surah:20 Taa-Haa", icon: FontAwesomeIcons.bookOpen),
//  Category(21,"Surah:21 Al-Anbiyaa", icon: FontAwesomeIcons.bookOpen),
//  Category(22,"Surah:22 Al-Hajj", icon: FontAwesomeIcons.bookOpen),
//  Category(23,"Surah:23 Al-Muminoon", icon: FontAwesomeIcons.bookOpen),
//  Category(24,"Surah:24 An-Noor", icon: FontAwesomeIcons.bookOpen),
//  Category(25,"Surah:25 Al-Furqaan", icon: FontAwesomeIcons.bookOpen),
//  Category(26,"Surah:26 Ash-Shu'araa", icon: FontAwesomeIcons.bookOpen),
//  Category(27,"Surah:27 An-Naml", icon: FontAwesomeIcons.bookOpen),
//  Category(28,"Surah:28 Al-Qasas", icon: FontAwesomeIcons.bookOpen),
//  Category(29,"Surah:29 Al-Ankaboot", icon: FontAwesomeIcons.bookOpen),
//  Category(30,"Surah:30 Ar-Room", icon: FontAwesomeIcons.bookOpen),
//  Category(31,"Surah:31 Luqman", icon: FontAwesomeIcons.bookOpen),
//  Category(32,"Surah:32 As-Sajda", icon: FontAwesomeIcons.bookOpen),
//  Category(33,"Surah:33 Al-Ahzaab", icon: FontAwesomeIcons.bookOpen),
//  Category(34,"Surah:34 Saba", icon: FontAwesomeIcons.bookOpen),
//  Category(35,"Surah:35 Faatir", icon: FontAwesomeIcons.bookOpen),
//  Category(36,"Surah:36 Yaseen", icon: FontAwesomeIcons.bookOpen),
//  Category(37,"Surah:37 As-Saaffaat", icon: FontAwesomeIcons.bookOpen),
//  Category(38,"Surah:38 Saad", icon: FontAwesomeIcons.bookOpen),
//  Category(39,"Surah:39 Az-Zumar", icon: FontAwesomeIcons.bookOpen),
//  Category(40,"Surah:40 Ghafir", icon: FontAwesomeIcons.bookOpen),
//  Category(41,"Surah:41 Fussilat", icon: FontAwesomeIcons.bookOpen),
//  Category(42,"Surah:42 Ash-Shura", icon: FontAwesomeIcons.bookOpen),
//  Category(43,"Surah:43 Az-Zukhruf", icon: FontAwesomeIcons.bookOpen),
//  Category(44,"Surah:44 Ad-Dukhaan", icon: FontAwesomeIcons.bookOpen),
//  Category(45,"Surah:45 Al-Jaathiya", icon: FontAwesomeIcons.bookOpen),
//  Category(46,"Surah:46 Al-Ahqaf", icon: FontAwesomeIcons.bookOpen),
//  Category(47,"Surah:47 Muhammad", icon: FontAwesomeIcons.bookOpen),
//  Category(48,"Surah:48 Al-Fath", icon: FontAwesomeIcons.bookOpen),
//  Category(49,"Surah:49 Al-Hujuraat", icon: FontAwesomeIcons.bookOpen),
//  Category(50,"Surah:50 Qaaf", icon: FontAwesomeIcons.bookOpen),
//  Category(51,"Surah:51 Adh-Dhaariyat", icon: FontAwesomeIcons.bookOpen),
//  Category(52,"Surah:52 At-Tur", icon: FontAwesomeIcons.bookOpen),
//  Category(53,"Surah:53 An-Najm", icon: FontAwesomeIcons.bookOpen),
//  Category(54,"Surah:54 Al-Qamar", icon: FontAwesomeIcons.bookOpen),
//  Category(55,"Surah:55 Ar-Rahmaan", icon: FontAwesomeIcons.bookOpen),
//  Category(56,"Surah:56 Al-Waaqia", icon: FontAwesomeIcons.bookOpen),
//  Category(57,"Surah:57 Al-Hadid", icon: FontAwesomeIcons.bookOpen),
//  Category(58,"Surah:58 Al-Mujaadila", icon: FontAwesomeIcons.bookOpen),
//  Category(59,"Surah:59 Al-Hashr", icon: FontAwesomeIcons.bookOpen),
//  Category(60,"Surah:60 Al-Mumtahana", icon: FontAwesomeIcons.bookOpen),
//  Category(61,"Surah:61 As-Saff", icon: FontAwesomeIcons.bookOpen),
//  Category(62,"Surah:62 Al-Jumu'a", icon: FontAwesomeIcons.bookOpen),
//  Category(63,"Surah:63 Al-Munaafiqoon", icon: FontAwesomeIcons.bookOpen),
//  Category(64,"Surah:64 At-Taghaabun", icon: FontAwesomeIcons.bookOpen),
//  Category(65,"Surah:65 At-Talaaq", icon: FontAwesomeIcons.bookOpen),
//  Category(66,"Surah:66 At-Tahrim", icon: FontAwesomeIcons.bookOpen),
//  Category(67,"Surah:67 Al-Mulk", icon: FontAwesomeIcons.bookOpen),
//  Category(68,"Surah:68 Al-Qalam", icon: FontAwesomeIcons.bookOpen),
//  Category(69,"Surah:69 Al-Haaqqa", icon: FontAwesomeIcons.bookOpen),
//  Category(70,"Surah:70 Al-Ma'aarij", icon: FontAwesomeIcons.bookOpen),
//  Category(71,"Surah:71 Nooh", icon: FontAwesomeIcons.bookOpen),
//  Category(72,"Surah:72 Al-Jinn", icon: FontAwesomeIcons.bookOpen),
//  Category(73,"Surah:73 Al-Muzzammil", icon: FontAwesomeIcons.bookOpen),
//  Category(74,"Surah:74 Al-Muddaththir", icon: FontAwesomeIcons.bookOpen),
//  Category(75,"Surah:75 Al-Qiyaama", icon: FontAwesomeIcons.bookOpen),
//  Category(76,"Surah:76 Al-Insaan", icon: FontAwesomeIcons.bookOpen),
//  Category(77,"Surah:77 Al-Mursalaat", icon: FontAwesomeIcons.bookOpen),
//  Category(78,"Surah:78 An-Naba", icon: FontAwesomeIcons.bookOpen),
//  Category(79,"Surah:79 An-Naazi'aat", icon: FontAwesomeIcons.bookOpen),
//  Category(80,"Surah:80 Abasa", icon: FontAwesomeIcons.bookOpen),
//  Category(81,"Surah:81 At-Takwir", icon: FontAwesomeIcons.bookOpen),
//  Category(82,"Surah:82 Al-Infitaar", icon: FontAwesomeIcons.bookOpen),
//  Category(83,"Surah:83 Al-Mutaffifin", icon: FontAwesomeIcons.bookOpen),
//  Category(84,"Surah:84 Al-Inshiqaaq", icon: FontAwesomeIcons.bookOpen),
//  Category(85,"Surah:85 Al-Burooj", icon: FontAwesomeIcons.bookOpen),
//  Category(86,"Surah:86 At-Taariq", icon: FontAwesomeIcons.bookOpen),
//  Category(87,"Surah:87 Al-A'laa", icon: FontAwesomeIcons.bookOpen),
//  Category(88,"Surah:88 Al-Ghaashiya", icon: FontAwesomeIcons.bookOpen),
//  Category(89,"Surah:89 Al-Fajr", icon: FontAwesomeIcons.bookOpen),
//  Category(90,"Surah:90 Al-Balad", icon: FontAwesomeIcons.bookOpen),
//  Category(91,"Surah:91 Ash-Shams", icon: FontAwesomeIcons.bookOpen),
//  Category(92,"Surah:92 Al-Lail", icon: FontAwesomeIcons.bookOpen),
//  Category(93,"Surah:93 Ad-Dhuhaa", icon: FontAwesomeIcons.bookOpen),
//  Category(94,"Surah:94 Ash-Sharh", icon: FontAwesomeIcons.bookOpen),
//  Category(95,"Surah:95 At-Tin", icon: FontAwesomeIcons.bookOpen),
//  Category(96,"Surah:96 Al-Alaq", icon: FontAwesomeIcons.bookOpen),
//  Category(97,"Surah:97 Al-Qadr", icon: FontAwesomeIcons.bookOpen),
//  Category(98,"Surah:98 Al-Bayyina", icon: FontAwesomeIcons.bookOpen),
//  Category(99,"Surah:99 Az-Zalzala", icon: FontAwesomeIcons.bookOpen),
//  Category(100 ,"Surah:100 Al-Aadiyaat", icon: FontAwesomeIcons.bookOpen),
//  Category(101 ,"Surah:101 Al-Qaari'a", icon: FontAwesomeIcons.bookOpen),
//  Category(102 ,"Surah:102 At-Takaathur", icon: FontAwesomeIcons.bookOpen),
//  Category(103 ,"Surah:103 Al-Asr", icon: FontAwesomeIcons.bookOpen),
//  Category(104 ,"Surah:104 Al-Humaza", icon: FontAwesomeIcons.bookOpen),
//  Category(105 ,"Surah:105 Al-Fil", icon: FontAwesomeIcons.bookOpen),
//  Category(106 ,"Surah:106 Quraish", icon: FontAwesomeIcons.bookOpen),
//  Category(107 ,"Surah:107 Al-Maa'un", icon: FontAwesomeIcons.bookOpen),
//  Category(108 ,"Surah:108 Al-Kawthar", icon: FontAwesomeIcons.bookOpen),
//  Category(109 ,"Surah:109 Al-Kaafiroon", icon: FontAwesomeIcons.bookOpen),
//  Category(110 ,"Surah:110 An-Nasr", icon: FontAwesomeIcons.bookOpen),
//  Category(111 ,"Surah:111 Al-Masad", icon: FontAwesomeIcons.bookOpen),
//  Category(112 ,"Surah:112 Al-Ikhlaas", icon: FontAwesomeIcons.bookOpen),
//  Category(113 ,"Surah:113 Al-Falaq", icon: FontAwesomeIcons.bookOpen),
//  Category(114 ,"Surah:114 An-Naas", icon: FontAwesomeIcons.bookOpen),
//];

final List<Category> categories = [
  Category(114 ,"Surah:114 An-Naas", icon: FontAwesomeIcons.bookOpen),
  Category(113 ,"Surah:113 Al-Falaq", icon: FontAwesomeIcons.bookOpen),
  Category(112 ,"Surah:112 Al-Ikhlaas", icon: FontAwesomeIcons.bookOpen),
  Category(111 ,"Surah:111 Al-Masad", icon: FontAwesomeIcons.bookOpen),
  Category(110 ,"Surah:110 An-Nasr", icon: FontAwesomeIcons.bookOpen),
  Category(109 ,"Surah:109 Al-Kaafiroon", icon: FontAwesomeIcons.bookOpen),
  Category(108 ,"Surah:108 Al-Kawthar", icon: FontAwesomeIcons.bookOpen),
  Category(107 ,"Surah:107 Al-Maa'un", icon: FontAwesomeIcons.bookOpen),
  Category(106 ,"Surah:106 Quraish", icon: FontAwesomeIcons.bookOpen),
  Category(105 ,"Surah:105 Al-Fil", icon: FontAwesomeIcons.bookOpen),
  Category(104 ,"Surah:104 Al-Humaza", icon: FontAwesomeIcons.bookOpen),
  Category(103 ,"Surah:103 Al-Asr", icon: FontAwesomeIcons.bookOpen),
  Category(102 ,"Surah:102 At-Takaathur", icon: FontAwesomeIcons.bookOpen),
  Category(101 ,"Surah:101 Al-Qaari'a", icon: FontAwesomeIcons.bookOpen),
  Category(100 ,"Surah:100 Al-Aadiyaat", icon: FontAwesomeIcons.bookOpen),
  Category(99,"Surah:99 Az-Zalzala", icon: FontAwesomeIcons.bookOpen),
  Category(98,"Surah:98 Al-Bayyina", icon: FontAwesomeIcons.bookOpen),
  Category(97,"Surah:97 Al-Qadr", icon: FontAwesomeIcons.bookOpen),
  Category(96,"Surah:96 Al-Alaq", icon: FontAwesomeIcons.bookOpen),
  Category(95,"Surah:95 At-Tin", icon: FontAwesomeIcons.bookOpen),
  Category(94,"Surah:94 Ash-Sharh", icon: FontAwesomeIcons.bookOpen),
  Category(93,"Surah:93 Ad-Dhuhaa", icon: FontAwesomeIcons.bookOpen),
  Category(92,"Surah:92 Al-Lail", icon: FontAwesomeIcons.bookOpen),
  Category(91,"Surah:91 Ash-Shams", icon: FontAwesomeIcons.bookOpen),
  Category(90,"Surah:90 Al-Balad", icon: FontAwesomeIcons.bookOpen),
  Category(89,"Surah:89 Al-Fajr", icon: FontAwesomeIcons.bookOpen),
  Category(88,"Surah:88 Al-Ghaashiya", icon: FontAwesomeIcons.bookOpen),
  Category(87,"Surah:87 Al-A'laa", icon: FontAwesomeIcons.bookOpen),
  Category(86,"Surah:86 At-Taariq", icon: FontAwesomeIcons.bookOpen),
  Category(85,"Surah:85 Al-Burooj", icon: FontAwesomeIcons.bookOpen),
  Category(84,"Surah:84 Al-Inshiqaaq", icon: FontAwesomeIcons.bookOpen),
  Category(83,"Surah:83 Al-Mutaffifin", icon: FontAwesomeIcons.bookOpen),
  Category(82,"Surah:82 Al-Infitaar", icon: FontAwesomeIcons.bookOpen),
  Category(81,"Surah:81 At-Takwir", icon: FontAwesomeIcons.bookOpen),
  Category(80,"Surah:80 Abasa", icon: FontAwesomeIcons.bookOpen),
  Category(79,"Surah:79 An-Naazi'aat", icon: FontAwesomeIcons.bookOpen),
  Category(78,"Surah:78 An-Naba", icon: FontAwesomeIcons.bookOpen),
  Category(77,"Surah:77 Al-Mursalaat", icon: FontAwesomeIcons.bookOpen),
  Category(76,"Surah:76 Al-Insaan", icon: FontAwesomeIcons.bookOpen),
  Category(75,"Surah:75 Al-Qiyaama", icon: FontAwesomeIcons.bookOpen),
  Category(74,"Surah:74 Al-Muddaththir", icon: FontAwesomeIcons.bookOpen),
  Category(73,"Surah:73 Al-Muzzammil", icon: FontAwesomeIcons.bookOpen),
  Category(72,"Surah:72 Al-Jinn", icon: FontAwesomeIcons.bookOpen),
  Category(71,"Surah:71 Nooh", icon: FontAwesomeIcons.bookOpen),
  Category(70,"Surah:70 Al-Ma'aarij", icon: FontAwesomeIcons.bookOpen),
  Category(69,"Surah:69 Al-Haaqqa", icon: FontAwesomeIcons.bookOpen),
  Category(68,"Surah:68 Al-Qalam", icon: FontAwesomeIcons.bookOpen),
  Category(67,"Surah:67 Al-Mulk", icon: FontAwesomeIcons.bookOpen),
  Category(66,"Surah:66 At-Tahrim", icon: FontAwesomeIcons.bookOpen),
  Category(65,"Surah:65 At-Talaaq", icon: FontAwesomeIcons.bookOpen),
  Category(64,"Surah:64 At-Taghaabun", icon: FontAwesomeIcons.bookOpen),
  Category(63,"Surah:63 Al-Munaafiqoon", icon: FontAwesomeIcons.bookOpen),
  Category(62,"Surah:62 Al-Jumu'a", icon: FontAwesomeIcons.bookOpen),
  Category(61,"Surah:61 As-Saff", icon: FontAwesomeIcons.bookOpen),
  Category(60,"Surah:60 Al-Mumtahana", icon: FontAwesomeIcons.bookOpen),
  Category(59,"Surah:59 Al-Hashr", icon: FontAwesomeIcons.bookOpen),
  Category(58,"Surah:58 Al-Mujaadila", icon: FontAwesomeIcons.bookOpen),
  Category(57,"Surah:57 Al-Hadid", icon: FontAwesomeIcons.bookOpen),
  Category(56,"Surah:56 Al-Waaqia", icon: FontAwesomeIcons.bookOpen),
  Category(55,"Surah:55 Ar-Rahmaan", icon: FontAwesomeIcons.bookOpen),
  Category(54,"Surah:54 Al-Qamar", icon: FontAwesomeIcons.bookOpen),
  Category(53,"Surah:53 An-Najm", icon: FontAwesomeIcons.bookOpen),
  Category(52,"Surah:52 At-Tur", icon: FontAwesomeIcons.bookOpen),
  Category(51,"Surah:51 Adh-Dhaariyat", icon: FontAwesomeIcons.bookOpen),
  Category(50,"Surah:50 Qaaf", icon: FontAwesomeIcons.bookOpen),
  Category(49,"Surah:49 Al-Hujuraat", icon: FontAwesomeIcons.bookOpen),
  Category(48,"Surah:48 Al-Fath", icon: FontAwesomeIcons.bookOpen),
  Category(47,"Surah:47 Muhammad", icon: FontAwesomeIcons.bookOpen),
  Category(46,"Surah:46 Al-Ahqaf", icon: FontAwesomeIcons.bookOpen),
  Category(45,"Surah:45 Al-Jaathiya", icon: FontAwesomeIcons.bookOpen),
  Category(44,"Surah:44 Ad-Dukhaan", icon: FontAwesomeIcons.bookOpen),
  Category(43,"Surah:43 Az-Zukhruf", icon: FontAwesomeIcons.bookOpen),
  Category(42,"Surah:42 Ash-Shura", icon: FontAwesomeIcons.bookOpen),
  Category(41,"Surah:41 Fussilat", icon: FontAwesomeIcons.bookOpen),
  Category(40,"Surah:40 Ghafir", icon: FontAwesomeIcons.bookOpen),
  Category(39,"Surah:39 Az-Zumar", icon: FontAwesomeIcons.bookOpen),
  Category(38,"Surah:38 Saad", icon: FontAwesomeIcons.bookOpen),
  Category(37,"Surah:37 As-Saaffaat", icon: FontAwesomeIcons.bookOpen),
  Category(36,"Surah:36 Yaseen", icon: FontAwesomeIcons.bookOpen),
  Category(35,"Surah:35 Faatir", icon: FontAwesomeIcons.bookOpen),
  Category(34,"Surah:34 Saba", icon: FontAwesomeIcons.bookOpen),
  Category(33,"Surah:33 Al-Ahzaab", icon: FontAwesomeIcons.bookOpen),
  Category(32,"Surah:32 As-Sajda", icon: FontAwesomeIcons.bookOpen),
  Category(31,"Surah:31 Luqman", icon: FontAwesomeIcons.bookOpen),
  Category(30,"Surah:30 Ar-Room", icon: FontAwesomeIcons.bookOpen),
  Category(29,"Surah:29 Al-Ankaboot", icon: FontAwesomeIcons.bookOpen),
  Category(28,"Surah:28 Al-Qasas", icon: FontAwesomeIcons.bookOpen),
  Category(27,"Surah:27 An-Naml", icon: FontAwesomeIcons.bookOpen),
  Category(26,"Surah:26 Ash-Shu'araa", icon: FontAwesomeIcons.bookOpen),
  Category(25,"Surah:25 Al-Furqaan", icon: FontAwesomeIcons.bookOpen),
  Category(24,"Surah:24 An-Noor", icon: FontAwesomeIcons.bookOpen),
  Category(23,"Surah:23 Al-Muminoon", icon: FontAwesomeIcons.bookOpen),
  Category(22,"Surah:22 Al-Hajj", icon: FontAwesomeIcons.bookOpen),
  Category(21,"Surah:21 Al-Anbiyaa", icon: FontAwesomeIcons.bookOpen),
  Category(20,"Surah:20 Taa-Haa", icon: FontAwesomeIcons.bookOpen),
  Category(19,"Surah:19 Maryam", icon: FontAwesomeIcons.bookOpen),
  Category(18,"Surah:18 Al-Kahf", icon: FontAwesomeIcons.bookOpen),
  Category(17,"Surah:17 Al-Israa", icon: FontAwesomeIcons.bookOpen),
  Category(16,"Surah:16 An-Nahl", icon: FontAwesomeIcons.bookOpen),
  Category(15,"Surah:15 Al-Hijr", icon: FontAwesomeIcons.bookOpen),
  Category(14,"Surah:14 Ibrahim", icon: FontAwesomeIcons.bookOpen),
  Category(13,"Surah:13 Ar-Ra'd", icon: FontAwesomeIcons.bookOpen),
  Category(12,"Surah:12 Yusuf", icon: FontAwesomeIcons.bookOpen),
  Category(11,"Surah:11 Hud", icon: FontAwesomeIcons.bookOpen),
  Category(10,"Surah:10 Yunus", icon: FontAwesomeIcons.bookOpen),
  Category(9 ,"Surah:9 At-Tawba", icon: FontAwesomeIcons.bookOpen),
  Category(8 ,"Surah:8 Al-Anfaal", icon: FontAwesomeIcons.bookOpen),
  Category(7 ,"Surah:7 Al-A'raaf", icon: FontAwesomeIcons.bookOpen),
  Category(6 ,"Surah:6 Al-An'aam", icon: FontAwesomeIcons.bookOpen),
  Category(5 ,"Surah:5 Al-Maaida", icon: FontAwesomeIcons.bookOpen),
  Category(4 ,"Surah:4 An-Nisaa", icon: FontAwesomeIcons.bookOpen),
  Category(3 ,"Surah:3 Aal-i-Imraan", icon: FontAwesomeIcons.bookOpen),
  Category(2 ,"Surah:2 Al-Baqara", icon: FontAwesomeIcons.bookOpen),
  Category(1 ,"Surah:1 Al-Faatiha", icon: FontAwesomeIcons.bookOpen)
];

